INSERT INTO USERINFO(USERID,NICK,USERPW,USERNAME,ADDR,PHONENUM,EMAIL) VALUES('incheon94','인천쓰', '1234', '1234', '1234', '1234', '1234');

SELECT * FROM USERINFO;


// 장바구니 등록
INSERT INTO FAVOR(FAVORNUM,USERID,UNIQUENUM) VALUES(
    2,(SELECT USERID FROM USERINFO WHERE USERID = 'incheon94'),(SELECT ITEM_NUM FROM GOODS_TABLE WHERE ITEM_NUM ='20')
    );
// 판매등록
INSERT INTO SALES_TABLE () VALUES(
    2,(SELECT USERID FROM USERINFO WHERE USERID = 'incheon94'),(SELECT ITEM_NUM FROM GOODS_TABLE WHERE ITEM_NUM ='20')
    );
// 조회수 증가
UPDATE GOODS_TABLE SET I_HIT = I_HIT+1 WHERE ITEM_NUM = '20';

// 취소 등록
DELETE FROM SALES_TABLE WHERE 판매NUM = '22';

// 판매 리스트 출력
SELECT * FROM SALES_TABLE WHERE USERID = 'incheon94' ;

SELECT SALES_TABLE.SALE_NUM ,SALES_TABLE.USERID ,SALES_TABLE.ITEM_NUM ,SALES_TABLE.I_DATE ,SALES_TABLE.DATE_NUM,SALES_TABLE.PERSON,GOODS_TABLE.TITLE FROM SALES_TABLE LEFT JOIN GOODS_TABLE ON SALES_TABLE.ITEM_NUM = GOODS_TABLE.ITEM_NUM WHERE SALES_TABLE.USERID = 'incheon94';



SELECT * FROM SALES_TABLE;


CREATE TABLE SALES_TABLE(SALE_NUM VARCHAR(100),USERID VARCHAR(100),ITEM_NUM VARCHAR(100),I_DATE DATE,DATE_NUM NUMBER,PERSON NUMBER);



INSERT INTO USERINFO(USERID,NICK,USERPW,USERNAME,ADDR,PHONENUM,EMAIL) VALUES('incheon94','인천쓰', '1234', '1234', '1234', '1234', '1234');
SELECT * FROM FAVOR;
SELECT * FROM USERINFO;
SELECT * FROM GOODS_TABLE;






CREATE TABLE USERINFO 
(
  USERID VARCHAR2(50 BYTE) NOT NULL 
, NICK VARCHAR2(50 BYTE) NOT NULL 
, USERPW VARCHAR2(50 BYTE) NOT NULL 
, USERNAME VARCHAR2(50 BYTE) NOT NULL 
, ADDR VARCHAR2(100 BYTE) 
, PHONENUM VARCHAR2(13 BYTE) 
, EMAIL VARCHAR2(50 BYTE) );

CREATE TABLE FAVOR 
(
  FAVORNUM NUMBER NOT NULL 
, USERID VARCHAR2(50 BYTE) 
, UNIQUENUM NUMBER NOT NULL );

CREATE TABLE REPLY 
(
  COMMENT_NUM NUMBER NOT NULL 
, TRAVERL_COMMENT VARCHAR2(1000 BYTE) NOT NULL 
, USERID VARCHAR2(50 BYTE) NOT NULL 
, TRAVEL_SCOPE NUMBER 
, TRAVEL_WRITEDATE DATE 
, GROUP_VALUE VARCHAR2(20 BYTE) 
, TRAVEL_NUM VARCHAR2(20 BYTE) 
, BOARDNUM NUMBER );

CREATE TABLE BOARD 
(
  BOARDNUM NUMBER NOT NULL 
, USERID VARCHAR2(50 BYTE) 
, REPORTINGDATE DATE NOT NULL 
, VIEWS NUMBER 
, TITLE VARCHAR2(100 BYTE) 
, CONTENT1 CLOB );


CREATE SEQUENCE SIRIAL_NUM MINVALUE 1 START WITH 1 INCREMENT BY 1;

INSERT INTO SALES_TABLE (SALE_NUM,USERID,ITEM_NUM,I_DATE,DATE_NUM,PERSON) VALUES ('S' || SIRIAL_NUM.NEXTVAL,'icnehons94','2',TO_DATE('2023-01-02','YYYY-MM-DD'),'3','1');


SELECT * FROM SALES_TABLE;